### ISSUE TITLE
Tweaking the UI: Firefox settings for font and background color

### ISSUE THREAD

**Issue by jdlk** [feedbin/support#162]
As I mentioned [in another thread](https://github.com/feedbin/support/issues/160), I'd prefer a different font and background color for the reading pane in Feedbin. In case it helps anyone else, this is the code I have added to my UserContent.css file to change the settings for Feedbin in Firefox. I'm no CSS expert but it seems to work okay:

``` css
@namespace url(http://www.w3.org/1999/xhtml);
/* Feedbin font and leading for third column */
@-moz-document domain(feedbin.me) {
  body
  {     font-family:Calibri, sans-serif !important;
        font-size:14px !important;
        line-height:19px !important;
  }
 /* Feedbin background color of third column */
  .entry-content
  {     background-color:#DCDCDC !important;
  } 
}
```
